### ISSUE TITLE
Compiling Error(Arduino)

### ISSUE THREAD

**Issue by SShultz75** [samyk/usbdriveby#10]
Arduino: 1.6.12 (Windows 10), Board: "Arduino/Genuino Uno"

C:\Users\Mr. Shultz\Documents\Arduino\USBdrivebyWindowsOS\USBdrivebyWindowsOS.ino: In function 'void openapp(String)':

USBdrivebyWindowsOS:33: error: 'KEY_R' was not declared in this scope

   key(KEY_R , MODIFIERKEY_RIGHT_GUI);

       ^

USBdrivebyWindowsOS:33: error: 'MODIFIERKEY_RIGHT_GUI' was not declared in this scope

   key(KEY_R , MODIFIERKEY_RIGHT_GUI);

               ^

USBdrivebyWindowsOS:37: error: 'Keyboard' not found. Does your sketch include the line '#include <Keyboard.h>'?
   Keyboard.print(app);

   ^

USBdrivebyWindowsOS:38: error: 'KEY_ENTER' was not declared in this scope

   key(KEY_ENTER, 0);

       ^

C:\Users\Mr. Shultz\Documents\Arduino\USBdrivebyWindowsOS\USBdrivebyWindowsOS.ino: In function 'void key(int, int)':

USBdrivebyWindowsOS:45: error: 'Keyboard' not found. Does your sketch include the line '#include <Keyboard.h>'?
   Keyboard.set_modifier(MODIFIER);

   ^

C:\Users\Mr. Shultz\Documents\Arduino\USBdrivebyWindowsOS\USBdrivebyWindowsOS.ino: In function 'void waitForDrivers()':

USBdrivebyWindowsOS:57: error: 'keyboard_leds' was not declared in this scope

   while (!(keyboard_leds & 2))

            ^

USBdrivebyWindowsOS:59: error: 'KEY_CAPS_LOCK' was not declared in this scope

     key(KEY_CAPS_LOCK, 0);

         ^

USBdrivebyWindowsOS:61: error: 'keyboard_leds' was not declared in this scope

   if (keyboard_leds & 2)

       ^

USBdrivebyWindowsOS:63: error: 'KEY_CAPS_LOCK' was not declared in this scope

     key(KEY_CAPS_LOCK, 0);

         ^

C:\Users\Mr. Shultz\Documents\Arduino\USBdrivebyWindowsOS\USBdrivebyWindowsOS.ino: In function 'void pwn()':

USBdrivebyWindowsOS:71: error: 'Keyboard' not found. Does your sketch include the line '#include <Keyboard.h>'?
   Keyboard.println("cd AppData/Local/Temp");

   ^

USBdrivebyWindowsOS:85: error: 'KEY_F4' was not declared in this scope

   key(KEY_F4, MODIFIERKEY_ALT);

       ^

USBdrivebyWindowsOS:85: error: 'MODIFIERKEY_ALT' was not declared in this scope

   key(KEY_F4, MODIFIERKEY_ALT);

               ^

USBdrivebyWindowsOS:87: error: 'KEY_ENTER' was not declared in this scope

   key(KEY_ENTER, 0);

       ^

USBdrivebyWindowsOS:94: error: 'KEY_SPACE' was not declared in this scope

   key(KEY_SPACE, MODIFIERKEY_ALT);

       ^

USBdrivebyWindowsOS:96: error: 'KEY_C' was not declared in this scope

   key(KEY_C, 0);

       ^

exit status 1
'KEY_R' was not declared in this scope

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by samyk** [comment]
Select "Serial+Keyboard+Mouse+Joystick" from Tools->USB Type

**Comment by SShultz75** [comment]
the "Tools->USB Type" no longer exists in the up to date Arduino IDE

**Comment by samyk** [comment]
Did you choose Teensy as the board type?
