### ISSUE TITLE
Windows version 

### ISSUE THREAD

**Issue by Bostrot** [samyk/usbdriveby#4]
Will you make a windows version too?

**Comment by samyk** [comment]
Probably not but happy to accept pull requests with cross platform support -- another user created a Windows version here actually https://github.com/Cryoganix/Teensyterpreter

**Comment by stefek99** [comment]
+1

**Comment by FFY00** [comment]
Submited a pull request.

**Comment by samyk** [comment]
No pull request has been submitted yet...

**Comment by FFY00** [comment]
Must be my git. Will submit again, thanks.

**Comment by samyk** [comment]
Awesome, merged! Thanks @FFY00!
